stages:
  prepare:
    cmd: uv run python src/prepare.py
    deps:
      - src/prepare.py
    params:
      - prepare
    outs:
      - data/train.csv
      - data/valid.csv
      - data/test.csv

  train:
    cmd: uv run python src/train.py
    deps:
      - src/train.py
      - src/common.py
      - data/train.csv
      - data/valid.csv
    params:
      - train
    outs:
      - model/model.joblib
    metrics:
      - metrics/valid.json:
          cache: false

  evaluate:
    cmd: uv run python src/evaluate.py
    deps:
      - src/evaluate.py
      - src/common.py
      - data/test.csv
      - model/model.joblib
    metrics:
      - metrics/test.json:
          cache: false
